using Me = Squeel.ThisAssembly;

namespace Squeel;

public static class GeneratedFileOptions
{
    public const string Header = $"""
        // <auto-generated>
        //   This file was generated by the source generator {Me.AssemblyName}
        //   
        //   Version      {Me.NuGetPackageVersion}
        //   SHA          {Me.GitCommitId}
        //   Repository   https://github.com/dotsef/squeel
        // </auto-generated>
        """;

    public const string Attribute = $"""
        [global::System.CodeDom.Compiler.GeneratedCode("{Me.AssemblyName}", "{Me.AssemblyInformationalVersion}")]
        """;
}